fix: deserialize IP address if returned by API
passbase/passbase-node pull request #3
Opened 2022-09-30 09:19 UTC by MrPrashantT

PR for issue [28773](https://app.shortcut.com/passbase-inc/story/28773/node-sdk-does-not-deserialize-expose-ip-address-ramp).

2022-09-30 13:25 UTC, mariusvirb requested changes
Please remove `package-lock.json`, otherwise lg2m

2022-10-03 12:14 UTC, MrPrashantT commented
> Please remove `package-lock.json`, otherwise lg2m

Done @mariusvirb

2022-10-04 06:31 UTC, mariusvirb requested changes
@MrPrashantT, this does not seem right :thinking: it seems package-lock **does** existing in our main branch :exploding_head: Well, since we didn't update any dependencies, please revert this file to it's original form.

2022-10-04 06:31 UTC, mariusvirb commented on src/models/Identity.ts
> +  network: {} | null;
Just noticed, this should be `Network`.

2022-10-04 11:04 UTC, MrPrashantT commented on src/models/Identity.ts
> +  network: {} | null;
Both fixed in latest commit.

2022-10-05 07:01 UTC, mariusvirb approved these changes, later dismissed
Perfect :lipstick:

2022-10-05 07:45 UTC, mariusvirb approved these changes

2022-10-05 08:26 UTC, merged